
@startuml 新規追加（詳細IFなし）

title 新規追加（詳細IFなし）

| 使用者 |
    :「新規作成」ボタン押下;
|#AntiqueWhite| アプリ |
    :「追加画面」遷移;
| 使用者 |
    :データ入力;
    :「作成」ボタン押下;
|#AntiqueWhite| アプリ |
    :DBにデータ保存;
    :ホーム画面を表示;
stop

@enduml